spring.application.name=mascotas

spring.datasource.url=jdbc:postgresql://dpg-d6ressfdiees73c7lac0-a.oregon-postgres.render.com:5432/mascotas_db_azh2
spring.datasource.username=mascotas_db_azh2_user
spring.datasource.password=21LmnZI6pqlAuBfNFyMRLxgPdKcLzXey
spring.datasource.driver-class-name=org.postgresql.Driver

#mostrar las consultas SQL
spring.jpa.show-sql=true

#configuracion para que actualice el esquema
spring.jpa.hibernate.ddl-auto=update

#dialecto de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect